name: Deploy to Serverless

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install Yarn 4
        run: |
          corepack enable
          yarn set version berry

      - name: Install serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: yarn install

      - name: Deploy Serverless
        run: |
          yarn run serverless config credentials --provider aws --key ${{ secrets.AWS_ACCESS_KEY_ID }} --secret ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          yarn start
